# -*- coding: utf-8 -*-
"""Untitled4.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/12sWAo8MFbr0UeR9qJtxs-azkUGMxAiVC
"""

import pandas as pd
df = pd.read_csv("tus_peliculas.csv")
print(df.head())  # Muestra las primeras filas

print(df["Género"].value_counts())

print(df["Duración (min)"].mean())

print(df["Plataforma"].value_counts())

import matplotlib.pyplot as plt
df["Género"].value_counts().plot(kind="pie", color="purple")
plt.title("Géneros más frecuentes")
plt.show()